### ISSUE TITLE
Stream.js example doesn't work?

### ISSUE THREAD

**Issue by NodeGuy** [telehash/telehash-js#38]
If I try the example after cloning the source from Github, it works.  If I try it from an `npm install telehash` then I get the following error:

```
bash-3.2$ node stream.js 
[Error: invalid public key data]
[Error: invalid public key data]

/Users/david/Documents/Toptal/clients/Eris-Industries/worker-hello-world/node_modules/telehash/examples/stream.js:9
meshA.mesh(meshB);
      ^
TypeError: Cannot call method 'mesh' of undefined
    at Object.<anonymous> (/Users/david/Documents/Toptal/clients/Eris-Industries/worker-hello-world/node_modules/telehash/examples/stream.js:9:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by NodeGuy** [comment]
I just reinstalled and now it's working; it must have been a fluke.
