### ISSUE TITLE
ws error: RangeError: out of range index

### ISSUE THREAD

**Issue by zlatinov** [telehash/telehash-js#58]
Windows 10, node v6.5.0, npm 3.10.5
The app is crashing in random times with this error:

```
Project\node_modules\telehash\node_modules\telehash-http\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\l
ib\Receiver.js:323
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (Project\node_modules\telehash\node_modules\telehash-http\node_modules\socket.io-client\node_modules\engine.io-client\
node_modules\ws\lib\Receiver.js:323:24)
    at Receiver.add (Project\node_modules\telehash\node_modules\telehash-http\node_modules\socket.io-client\node_modules\engine.io-cli
ent\node_modules\ws\lib\Receiver.js:84:3)
    at Socket.firstHandler (Project\node_modules\telehash\node_modules\telehash-http\node_modules\socket.io-client\node_modules\engine
.io-client\node_modules\ws\lib\WebSocket.js:678:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by ig0r** [comment]
I'm observing the same behaviour on Linux as well. Usually happens after uptime for 2-4 hours

**Comment by anhldbk** [comment]
@zlatinov , @ig0r : Looks like an error of package `socket.io-client`. Anway, this repo seems to not maintained well. I wonder if we should use it in production.
